name: flutter_image_compress_common
description: Compress image with native (Objective-C/Kotlin) with faster speed. Support Android/iOS.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 1.0.5

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface: ^1.0.5
  
flutter:
  plugin:
    implements: flutter_image_compress
    platforms:
      android:
        package: com.fluttercandies.flutter_image_compress
        pluginClass: ImageCompressPlugin
        dartPluginClass: FlutterImageCompressCommon
      ios:
        pluginClass: ImageCompressPlugin
        dartPluginClass: FlutterImageCompressCommon
