name: flutter_image_compress_platform_interface
description: The platform interface of flutter_image_compress.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 1.0.5

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  cross_file: ^0.3.3+2